In [1]:
import numpy as np
arr1=np.arange(0,10,1)
arr2=np.arange(10,20)
arr3=np.arange(10,20,3)
print(arr1)
print(arr2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 13 16 19]


### Difference between list and numpy array

### Aspects of cache:

In [ ]:
Spatial:
        --->Insted of loading one block load the consecutive block also.
Temporal aspect:
        --->Insted of loading consecutive block load the entire array.

In [3]:
import numpy as np
m1=[[1,2],[3,4]]
m2=[[3,4],[5,6]]
m3=[[0,0],[0,0]]
for i in range(len(m1)):
    for j in range(len(m2)):
        m3[i][j]=m1[i][j]+m2[i][j]
print(m3)

[[4, 6], [8, 10]]


In [5]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])
print(m1+m2)
print(m1.ndim)
print(m2.ndim)
print(type(m1))
print(type(m2))



[[ 6  8]
 [10 12]]
2
2
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[3,4],[5,6]])
print(a1+a2)
print(a1.ndim)
print(a2.ndim)
print(type(a1))
print(type(a2))

[[ 4  6]
 [ 8 10]]
2
2
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [31]:
### To do multiplication  number of rows * number of columns.
import numpy as np
m1=[[1,2],[3,4]]
m2=[[3,4],[5,6]]
m3=[[0,0],[0,0]]
for i in range(len(m1)):
    for j in range(len(m2)):
        for k in range(len(m2)):
            m3[i][j]+=m1[i][k]*m2[k][j]
print(m3)

[[13, 16], [29, 36]]


In [45]:
import numpy as np
m1=[[1,2],[3,4]]
m2=[[3,4],[5,6]]
m3=[[0,0],[0,0]]
for i in range(len(m1)):
    for j in range(len(m2)):
        m3[i][j]-=m1[i][j]-m2[i][j]
print(m3)

[[2, 2], [2, 2]]


In [47]:
###Creating numpy array using np.arrange()

import numpy as np
arr1=np.arange(0,10,1)
arr2=np.arange(10,20)
arr3=np.arange(10,20,3)
print(arr1)
print(arr2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 13 16 19]


In [49]:
### Creating the numpy as np.zeros()
import numpy as np
arr1=np.zeros(6)
arr2=np.zeros((2,2))
print(arr1)
print(arr2)
print(arr1.ndim)
print(arr2.ndim)
print(type(arr1))
print(type(arr2))

[0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
1
2
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
### Creating the numpy as np.ones()

import numpy as np
arr3=np.ones(5)
arr4=np.ones((3,3))
print(arr3)
print(arr4)
print(type(arr3))
print(type(arr4))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [13]:
### Creating the numpy as np.eye() ### It will make all the diagonal elements 1
import numpy as np
arr6=np.eye(5)
arr7=np.eye(3,3)
arr8=np.eye(4,4)
print(arr6)
print(arr7)
print(arr8)
print(arr6.ndim)
print(arr7.ndim)
print(arr8.ndim)
print(type(arr6))
print(type(arr7))
print(type(arr8))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
2
2
2
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [21]:
### Creating the numpy as np.diag()
import numpy as np
arr9=np.diag([1,2,3])
arr10=np.diag([1,2,3,4,5])
print(arr9.ndim)
print(arr10.ndim)
print(arr9)
print(arr10)
print(type(arr9))
print(type(arr10))

2
2
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [27]:
#############Creating the numpy array using the np.random.rand():#####################
### It will create the random values array as per the limit according to the uniform distribution.
import numpy as np
a=np.random.rand(5)
print(a)

[0.75897666 0.90267999 0.79713394 0.95691528 0.88794052]


In [133]:
###############Creating the numpy array using the np.random.rand():#########################
import numpy as np
a1=np.random.rand(3,3)
print(a1)

[[0.56910082 0.43393981 0.82519835]
 [0.60184678 0.57237074 0.89669701]
 [0.58685569 0.27121638 0.44246504]]


In [59]:
############## Creating the numpy array using the np.random.randn(): 

# It will also gives the random values as per the standared normal variate(standared normal distribution)

import numpy as np
b=np.random.randn(5)
print(b)

[-0.72549019 -0.13232865 -0.66215643  0.55804273 -0.94000013]


In [29]:
############ Creating the numpy array using the np.random.randint(): ############################
import numpy as np
c=np.random.randint(10,20,(3,3))
print(c)
print(type(c))

[[18 18 11]
 [16 19 18]
 [12 18 14]]
<class 'numpy.ndarray'>


In [37]:
############ Creating the numpy array using the np.copy(): ###################################

import numpy as np
a1=np.array([1,2,3,4,5,6])
a2=a1.copy()
print(a2)
print(type(a1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
