### Arthimatic operations on numpy"

In [ ]:
1.Matrix operations:
        --->Addition 
        --->Subtraction
        --->Multiplication
            --->Cross(+)
            --->Dot

2.Arthimatic operations:
        --->All the operations are done element wise
        --->Addition(+)
        --->Subtraction(-)
        --->Multiplication(*)
        --->Division(/)
        --->Floor Divisions(//)
        --->Power(**)

3. Scaler Operations:
        ---> All operations are done with a scaler.
        ---> array+1
        ---> np.ones((3,3))+1

4.Relational Operator:
        --->It is used to find the relation between the elements on the numpy array.
        ---> >,<,<=,>=,!-----------it will compare element wise
        --->np.array_equal(a1,a2)----it will compare array wise

5.logical Operator:
        --->We are using the logical operation to compare two or more expression.
        --->all()
                --->It will return true if every element is true
                --->every non zero is considered as true
        --->any():
                --->If at least one true it will return true
                --->np.any()
        --->logical_or():
                --->np.logical_or(a,b)
                --->It will return true if any one values is true otherwise False
        --->LOGICAL_AND():
                --->np.logical_and(a,b)
                --->It will return if both the values is true otherwise false

6.Transcendental operations:
        --->When we have a log,exp(e),trignomentry----
        --->np.log(): It will give the log of each value present in the numpy array.
        --->np.exp(): It is gving the exponential value of each elements of numpy array.
        --->Trignomentry:
                    --->np.sin()
                        --->It will consider all the values in radian
                    --->np.cos()
            --->a=np.array([3,4,5,6])
            --->np.sin(a)

7.Sorting:
        --->Sorting the element in ascending or descending order
            1.np.sort()
                --->It will sort in ascending order
                --->It will not in-place sort
                    --->a=np.array([1,4,7,-2,-4,0])
                        b=np.sort(a)
                            print(b)

                        mat1=np.array([[11,7,-2],[4,-6,17],[-23,18,-34]])
                        mat2=np.sort(mat1)
                        print(mat2)


                        mat1=np.array([[11,7,-2],[4,-6,17],[-23,18,-34]])
                        mat2=np.sort(mat1)---->Row wise sorting
                        mat3=np.sort(mat1,axis=0)----column wise sorting
                        print(mat1)
                        print(mat2)
                        print(mat3)


            2.np.argsort()
                --->It will perform the sorting in the basis of index of the numpy array
                a=np.array([1,4,7,-2,-4,0])
                print(np.argsort(a))

                        mat1=np.array([[11,7,-2],[4,-6,17],[-23,18,-34]])
                        print(np.argsort(mat1))

                        mat1=np.array([[11,7,-2],[4,-6,17],[-23,18,-34]])
                        print(np.argsort(mat1,axis=0))


            3.array.sort()
                --->It will perform sorting
                --->inplace sort
                a=np.array([1,4,7,-2,-4,0])
                print(a.sort())

                       mat1=np.array([[11,7,-2],[4,-6,17],[-23,18,-34]])
                       print(mat1.argsort()) 


8.Agrregation Operation:
        --->sum():
                -->np.sum(array)
        --->max():
                -->np.max(array)
        --->min():
                -->np.min(array)
        --->argmax(): it will give you max index
                -->np.argmax(array)
        --->argmin():
                -->np.argmin(array)

9.Searching in numpy array:
        --->1.)np.where(condition): It will return the index of the elements where the condition is true
                a=np.array([3,4,5,1,7])
                print(np.where(a>2))  ## here where a value is greater than 2 it is returing the index of that value.
                print(np.where(a==2))
                print(np.where(a==3)) output:
        --->2.)np.nonzero(): It will return the index of the non-zero elements in the array.
                SYNTAX: np.nonzero(array_name)
        --->3.)np.extract(): It will return the element based on the condition:
                SYNTAX: np.extract(condition,array_name)
       
10.Adding elements into array:
        --->1.)np.append(): It is used to add the elemet in the numpy array.
                        --->It will not make changes directly in exisiting array, we have to create a new array to see the changes.
                        --->It is taking the extra array for append.
                            SYNTAX: np.append(array,element)
        --->2.)np.insert(): It will insert the element into numpy array at the particular position.
                        --->But to see the changes we have create another numpy array.
                            SYNTAX: np.insert(array_name,index,ite,)
        --->3.)np.concatenate(): It is used to concatenate the numpy array to another numpy array.
                            --->It will create a numpy array.
                            SYNTAX: np.concatenate(array_name,([i1,i2,.....]))

11.Reshaping:
        --->It convert the one numpy array into another dimensions.
            SYNTAX: array_name=np.array([]).reshape(x_dim,y_dim)
                    array_name.reshape()
        --->Condition:
                    --->No.of elements before reshaping and after reshaping must be equal.
--->If only one row present ina a matrix: row vector:(a*n)
--->If only one column present in a matrix



In [3]:
### Sclar operation
import numpy as np
print(np.ones((3,3))+1)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [1]:
### Relational operator or compraision operator

import numpy as np
a1=np.array([1,2,3,4,5,6])
a2=np.array([2,1,4,3,6,5])
print(a1>a2)
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print("-------------------------------")
print(type(a1))
print(type(a2))

[False  True False  True False  True]
[ 3  3  7  7 11 11]
[-1  1 -1  1 -1  1]
[ 2  2 12 12 30 30]
[0.5        2.         0.75       1.33333333 0.83333333 1.2       ]
-------------------------------
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
a1 = [[0, 0], [0, 0]]
def fun(a1):
    for i in range(len(a1)):
        for j in range(len(a1)):  
            if a1[i][j]!=0:
                return False  
    return True  
print(fun(a1))


True


In [3]:
a=np.array([2,3,4,5,6,0])
print(np.log(a))
print(np.exp(a)) ## It is taking the exponential value

[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947       -inf]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349
   1.        ]


C:\Users\mahesh sai\AppData\Local\Temp\ipykernel_20116\617833044.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))


In [34]:
np.sin(a)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,
        0.        ])

In [36]:
np.cos(a)

array([-0.41614684, -0.9899925 , -0.65364362,  0.28366219,  0.96017029,
        1.        ])

In [42]:
import numpy as np
a=np.array([1,4,7,-2,-4,0])
b=np.sort(a)
print(b)
print(np.argsort(a))

[-4 -2  0  1  4  7]
[4 3 5 0 1 2]


In [5]:
import numpy as np
mat1=np.array([[11,7,-2],[4,-6,17],[-23,18,-34]])
mat2=np.sort(mat1)#---->Row wise sorting
mat3=np.sort(mat1,axis=0)#----column wise sorting
print(mat1)
print(mat2)
print(mat3)


[[ 11   7  -2]
 [  4  -6  17]
 [-23  18 -34]]
[[ -2   7  11]
 [ -6   4  17]
 [-34 -23  18]]
[[-23  -6 -34]
 [  4   7  -2]
 [ 11  18  17]]


In [50]:
### Sort function in reverse :
a=np.array([12,45,-2,0,34,778,23])
b=np.sort(a)[::-1]
c=np.sort(a)
print(b)
print(c)

[778  45  34  23  12   0  -2]
[ -2   0  12  23  34  45 778]


In [56]:
### Searching in numpy array: It will return the index of the elements where the condition is true
a=np.array([3,4,5,1,7])
print(np.where(a>2))  ## here where "a" value is greater than 2 it is returing the index of that value.
print(np.where(a==2))
print(np.where(a==3))

(array([0, 1, 2, 4], dtype=int64),)
(array([], dtype=int64),)
(array([0], dtype=int64),)


In [58]:
### Searching in numpy array:

### np.nonzero():

###  SYNTAX: np.nonzero(array_name)

### It will return the index of the non-zero elements in the array.

import numpy as np
b=np.array([2,3,4,0,5,6,0,0])
print(np.nonzero(b))

(array([0, 1, 2, 4, 5], dtype=int64),)


In [62]:
### Searching in numpy array:

### np.extract():

### SYNTAX: np.extract(condition,array_name)

### It will return the element based on the condition:

import numpy as np
c=np.array([4,5,6,11,19,20])
np.extract(c>5,c)

array([ 6, 11, 19, 20])

In [7]:
### np.insert(): 

###  SYNTAX: np.insert(array_name,index,item)

### It will insert the element into numpy array at the particular position.
import numpy as np
q=np.array([3,4,5,6,7,8,9])
r=np.insert(q,3,100)
print(r)

[  3   4   5 100   6   7   8   9]


In [66]:
### np.concatenate():

###  SYNTAX: np.concatenate(array_name,[i1,i2,.....])

### It is used to concatenate the numpy array to another numpy array.
import numpy as np
array1=np.array([45,67,89,90,100])
array2=np.concatenate((array1,np.array([1,2,3,4])))
print(array2)

[ 45  67  89  90 100   1   2   3   4]


In [78]:
### Reshaping:

###  SYNTAX: array_name=np.array([]).reshape(x_dim,y_dim)
                 #   array_name.reshape()
      #  --->Condition:
                   # --->No.of elements before reshaping and after reshaping must be equal.

import numpy as np
a1=np.array([1,2,3,4,5,6])
a1.size

6

In [92]:
a1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
12. Accessing the  elements in numpy array:

In [17]:
import numpy as np
a=np.array([2,3,4,5,6,7,8])
a[2]

4

In [19]:
import numpy as np
b=np.array([1,2],[3,4])
b[1][0]

TypeError: Field elements must be 2- or 3-tuples, got '3'