### NUMPY (Numerical Python)

### SYNTAX OF NUMPY:

In [ ]:
--->For using the numpy we need to import it.
SYNTAX:
        import numpy as np

import==keyword
numpy=library name
np=alias

Installing numpy: pip install numpyc

### CREATING NUMPY ARRAY:

In [ ]:
1.np array() : 
    --->We are creating the numpy array manually with help of np.array()
    --->It will always take list as argument

        SYNTAX: identifier/variable=np_array=np.array([e1,e2,e3,e4,e5])
--->Numpy is fixed size.

--->When we have 1 dimensional array we called it as vector.
--->Number of subscript operators will decide the dimensional of numpy array
        []--->1D
        [[]]--->2D

Syntax:
        array_name.ndim

In [1]:
import numpy as np
np_array=np.array([1,2,3,4,5])
print(np_array)
np_array.ndim

[1 2 3 4 5]


1

In [12]:
type(np_array)

numpy.ndarray

In [16]:
np_array.ndim ## ndim will gives you the no.of dimensions in the array.

1

In [15]:
import numpy as np
np_array2=np.array([[1,2,3,4],[6,7,8,9]])
print(np_array2)  ## THESE IS THE 2 DIMENSION ( 1st is rows and 2nd is columns)
print(np_array2.ndim)
type(np_array2)

[[1 2 3 4]
 [6 7 8 9]]
2


numpy.ndarray

In [17]:
import numpy as np
np_array3=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(np_array3)  ### THESE IS THE 3 DIMENSION
type(np_array3)
print(np_array3.ndim)


[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
3


In [13]:
import numpy as np
np_array4=np.array([[[[1,2],[3,4],[5,6],[7,8],[9,10]]]])
print(np_array4)
print(np_array4.ndim)
print(type(np_array4))

[[[[ 1  2]
   [ 3  4]
   [ 5  6]
   [ 7  8]
   [ 9 10]]]]
4
<class 'numpy.ndarray'>
