In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.itemsize) # bits
print(a.dtype)
print(a.trace)
print(a.astype("float"))

2
(2, 3)
6
4
int32
<built-in method trace of numpy.ndarray object at 0x000002F912F0B390>
[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
array=([[1,2,3],[4,5,6],[7,8,9]])
sum=0
print(array)
for i in range(len(array)):
    for j in range(len(array)):
        if i==j:
            sum+=array[i][j]
print(sum)
print(np.trace(array))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
15
15


### Methods:

In [21]:
aa=([[1,2],[3,4]])
b=[[0,0],[0,0]]
for i in range(len(a)):
    for j in range(len(a)):
        b[i][j]+=(a[i][j])
print(b)
print(np.linalg.det(aa))
print(np.linalg.matrix_rank(aa))

[[1, 2], [4, 5]]
-2.0000000000000004
2


### Scalar Operations:

In [60]:
a=np.array([1,2,3,4,5])
print(a+1)
print(a-1)
print(a*1)
print(a%1)

[2 3 4 5 6]
[0 1 2 3 4]
[1 2 3 4 5]
[0 0 0 0 0]
